### ISSUE TITLE
Pretrained models are missing

### ISSUE THREAD

**Issue by pleochroite** [masashi-y/abduction_kbc#1]
Hi, 
I successfully compiled coqlib.v on ubuntu 18.04 on AWS EC2.
Pretrained models (but also the directory cl.naist.jp/~masashi-y/resources/ ), however, seems to be missing...

**Comment by masashi-y** [comment]
Hello. Thank you for playing with my codes. I uploaded them to Google Drive and changed the links in the README accordingly. Please download them from there!

**Comment by pleochroite** [comment]
Successfully downloaded. Thanks!! I'll try following directions ^^
